homepage:
    path:     /
    defaults: { _controller: AcmeEvaluationBundle:Evaluation:index }

register:
    path:     /register
    defaults: { _controller: AcmeEvaluationBundle:Evaluation:register }