parameters:
#    acme_evaluation.example.class: Acme\EvaluationBundle\Example

services:
#    acme_evaluation.example:
#        class: %acme_evaluation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
